Add release workflow
ballerina-platform/module-ballerina-filepath pull request #10
Opened 2020-09-21 15:27 UTC by ThishaniLucas

$subject

2020-09-21 17:16 UTC, niveathika requested changes

2020-09-21 17:16 UTC, niveathika commented on .github/workflows/publish-release.yml
> +            GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
Wrong indendation

2020-09-22 04:29 UTC, BuddhiWathsala commented on build.gradle
> +    buildTasks = []
Need to add build config here as https://github.com/ballerina-platform/module-ballerina-websub/pull/24/commits/3c9c29f14ef8c4428dabaf0b085b5ec9ff41b4b7

2020-09-22 05:01 UTC, niveathika approved these changes

2020-09-22 05:04 UTC, merged